[package]
name = "nyaa"
version = "0.5.0"
edition = "2021"
categories = ["command-line-utilities"]
keywords = ["tui", "cli", "nyaa", "torrent", "download"]
description = "A tui tool for browsing and downloading torrents from nyaa.si"
readme = "README.md"
repository = "https://github.com/Beastwick18/nyaa/"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features=["gzip"]}
tokio = { version = "1.36.0", features=["rt", "macros", "rt-multi-thread"] }
urlencoding = "2.1.0"
ratatui = "0.25.0"
crossterm = "0.27.0"
unicode-width = "0.1.5"
confy = "0.6.0"
shellwords = "1.1.0"
serde = { version = "1.0.152", features = ["derive"] }
scraper = "0.18.1"
