[package]
name = "nyaa"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities"]
keywords = ["tui", "cli", "nyaa", "torrent", "download"]
description = "A tui tool for browsing and downloading torrents from nyaa.si"
readme = "README.md"
repository = "https://github.com/Beastwick18/nyaa/"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1.0"
tui = "0.19"
crossterm = "0.26.1"
unicode-width = "0.1.5"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
queues = "1.0.2"
confy = "0.5.1"
shellwords = "1.1.0"
serde = { version = "1.0.152", features = ["derive"] }
