[package]
name = "nyaa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1.0"
regex = "1"
log = "0.4"
config = "0.13.1"
dirs = "4.0.0"
tui = "0.19"
crossterm = "0.25"
unicode-width = "0.1.5"
throbber-widgets-tui = "0.1.3"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
